[2024-11-24T11:43:11.991+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T11:43:12.000+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T10:59:27.178098+00:00 [queued]>
[2024-11-24T11:43:12.006+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T10:59:27.178098+00:00 [queued]>
[2024-11-24T11:43:12.006+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-11-24T11:43:12.013+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_data> on 2024-11-24 10:59:27.178098+00:00
[2024-11-24T11:43:12.016+0000] {standard_task_runner.py:72} INFO - Started process 126 to run task
[2024-11-24T11:43:12.018+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_etl', 'collect_data', 'manual__2024-11-24T10:59:27.178098+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_auto.py', '--cfg-path', '/tmp/tmp6ijjj3u6']
[2024-11-24T11:43:12.020+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask collect_data
[2024-11-24T11:43:12.047+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T10:59:27.178098+00:00 [running]> on host 28b55c2984f3
[2024-11-24T11:43:12.088+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_etl' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T10:59:27.178098+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T10:59:27.178098+00:00'
[2024-11-24T11:43:12.089+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T11:43:12.100+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-24T11:43:12.101+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data-pipeline-project/product_data_scraper.py']
[2024-11-24T11:43:12.106+0000] {subprocess.py:99} INFO - Output:
[2024-11-24T12:03:12.128+0000] {timeout.py:68} ERROR - Process timed out, PID: 126
[2024-11-24T12:03:12.139+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-11-24T12:03:12.171+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 126
[2024-11-24T12:03:12.183+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_etl, task_id=collect_data, run_id=manual__2024-11-24T10:59:27.178098+00:00, execution_date=20241124T105927, start_date=20241124T114312, end_date=20241124T120312
[2024-11-24T12:03:12.199+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T12:03:12.230+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 2
[2024-11-24T12:03:12.255+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T12:03:12.256+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
