[2024-12-06T05:41:12.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T05:41:12.434+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-12-06T05:16:08.818590+00:00 [queued]>
[2024-12-06T05:41:12.437+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-12-06T05:16:08.818590+00:00 [queued]>
[2024-12-06T05:41:12.438+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-06T05:41:12.442+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_data> on 2024-12-06 05:16:08.818590+00:00
[2024-12-06T05:41:12.445+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=488) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-06T05:41:12.446+0000] {standard_task_runner.py:72} INFO - Started process 489 to run task
[2024-12-06T05:41:12.446+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_etl', 'collect_data', 'manual__2024-12-06T05:16:08.818590+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_auto.py', '--cfg-path', '/tmp/tmp2aryvkqe']
[2024-12-06T05:41:12.447+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask collect_data
[2024-12-06T05:41:12.464+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_etl.collect_data manual__2024-12-06T05:16:08.818590+00:00 [running]> on host 1e58f50a750b
[2024-12-06T05:41:12.493+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_etl' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T05:16:08.818590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T05:16:08.818590+00:00'
[2024-12-06T05:41:12.493+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T05:41:12.504+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-06T05:41:12.505+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data-pipeline-project/product_data_scraper.py']
[2024-12-06T05:41:12.509+0000] {subprocess.py:99} INFO - Output:
[2024-12-06T05:47:09.303+0000] {subprocess.py:106} INFO - 320번 데이터 수집 시작
[2024-12-06T05:47:09.307+0000] {subprocess.py:106} INFO - 페이지 5 데이터 수집 시작 (카테고리: 320)
[2024-12-06T05:47:09.307+0000] {subprocess.py:106} INFO - 데이터 수집중5
[2024-12-06T05:47:09.307+0000] {subprocess.py:106} INFO - 페이지 5 데이터 수집 완료 (카테고리: 320)
[2024-12-06T05:47:09.308+0000] {subprocess.py:106} INFO - 페이지 7 데이터 수집 시작 (카테고리: 320)
[2024-12-06T05:47:09.308+0000] {subprocess.py:106} INFO - 데이터 수집중7
[2024-12-06T05:47:09.308+0000] {subprocess.py:106} INFO - 페이지 7 데이터 수집 완료 (카테고리: 320)
[2024-12-06T05:47:09.308+0000] {subprocess.py:106} INFO - 페이지 6 데이터 수집 시작 (카테고리: 320)
[2024-12-06T05:47:09.309+0000] {subprocess.py:106} INFO - 데이터 수집중6
[2024-12-06T05:47:09.309+0000] {subprocess.py:106} INFO - 페이지 6 데이터 수집 완료 (카테고리: 320)
[2024-12-06T05:47:09.309+0000] {subprocess.py:106} INFO - 페이지 8 데이터 수집 시작 (카테고리: 320)
[2024-12-06T05:47:09.309+0000] {subprocess.py:106} INFO - 데이터 수집중8
[2024-12-06T05:47:09.309+0000] {subprocess.py:106} INFO - 페이지 8 데이터 수집 완료 (카테고리: 320)
[2024-12-06T05:47:09.310+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-12-06T05:47:09.310+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 84, in <module>
[2024-12-06T05:47:09.310+0000] {subprocess.py:106} INFO -     collect_all(320)
[2024-12-06T05:47:09.310+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 70, in collect_all
[2024-12-06T05:47:09.311+0000] {subprocess.py:106} INFO -     for page_data in results:
[2024-12-06T05:47:09.311+0000] {subprocess.py:106} INFO -                      ^^^^^^^
[2024-12-06T05:47:09.311+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
[2024-12-06T05:47:09.311+0000] {subprocess.py:106} INFO -     yield _result_or_cancel(fs.pop())
[2024-12-06T05:47:09.311+0000] {subprocess.py:106} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-06T05:47:09.311+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
[2024-12-06T05:47:09.311+0000] {subprocess.py:106} INFO -     return fut.result(timeout)
[2024-12-06T05:47:09.312+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^
[2024-12-06T05:47:09.312+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
[2024-12-06T05:47:09.312+0000] {subprocess.py:106} INFO -     return self.__get_result()
[2024-12-06T05:47:09.312+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^
[2024-12-06T05:47:09.312+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
[2024-12-06T05:47:09.312+0000] {subprocess.py:106} INFO -     raise self._exception
[2024-12-06T05:47:09.312+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -     result = self.fn(*self.args, **self.kwargs)
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 57, in fetch_page
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -     driver = webdriver.Remote(
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -              ^^^^^^^^^^^^^^^^^
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -     self.start_session(capabilities)
[2024-12-06T05:47:09.313+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO -     self.error_handler.check_response(response)
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO -     raise exception_class(message, screen, stacktrace)
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO - selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. New session request timed out
[2024-12-06T05:47:09.314+0000] {subprocess.py:106} INFO - Host info: host: '89855b5d2872', ip: '172.18.0.5'
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO - Build info: version: '4.20.0', revision: '866c76ca80'
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO - System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.14-linuxkit', java.version: '17.0.11'
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO - Driver info: driver.version: unknown
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:221)
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:68)
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
[2024-12-06T05:47:09.315+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.316+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-06T05:47:09.316+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.316+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:128)
[2024-12-06T05:47:09.316+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:87)
[2024-12-06T05:47:09.316+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-06T05:47:09.316+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-06T05:47:09.317+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.317+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.router.Router.execute (Router.java:87)
[2024-12-06T05:47:09.317+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
[2024-12-06T05:47:09.317+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-06T05:47:09.317+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-06T05:47:09.317+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:270)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-06T05:47:09.318+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-06T05:47:09.319+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
[2024-12-06T05:47:09.320+0000] {subprocess.py:106} INFO -     at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
[2024-12-06T05:47:09.320+0000] {subprocess.py:106} INFO -     at java.util.concurrent.FutureTask.run (None:-1)
[2024-12-06T05:47:09.320+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
[2024-12-06T05:47:09.320+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
[2024-12-06T05:47:09.320+0000] {subprocess.py:106} INFO -     at java.lang.Thread.run (None:-1)
[2024-12-06T05:47:09.372+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2024-12-06T05:47:09.388+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-06T05:47:09.394+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_etl, task_id=collect_data, run_id=manual__2024-12-06T05:16:08.818590+00:00, execution_date=20241206T051608, start_date=20241206T054112, end_date=20241206T054709
[2024-12-06T05:47:09.404+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T05:47:09.404+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task collect_data (Bash command failed. The command returned a non-zero exit code 1.; 489)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-06T05:47:09.437+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T05:47:09.450+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T05:47:09.451+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
