[2024-12-12T01:18:24.809+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T01:18:24.814+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data scheduled__2024-12-10T04:00:00+00:00 [queued]>
[2024-12-12T01:18:24.817+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data scheduled__2024-12-10T04:00:00+00:00 [queued]>
[2024-12-12T01:18:24.817+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-12T01:18:24.821+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_data> on 2024-12-10 04:00:00+00:00
[2024-12-12T01:18:24.824+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-12T01:18:24.824+0000] {standard_task_runner.py:72} INFO - Started process 262 to run task
[2024-12-12T01:18:24.824+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_etl', 'collect_data', 'scheduled__2024-12-10T04:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_auto.py', '--cfg-path', '/tmp/tmp6szlnp9a']
[2024-12-12T01:18:24.825+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask collect_data
[2024-12-12T01:18:24.840+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_etl.collect_data scheduled__2024-12-10T04:00:00+00:00 [running]> on host 88c81553e713
[2024-12-12T01:18:24.868+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_etl' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-10T04:00:00+00:00'
[2024-12-12T01:18:24.868+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T01:18:24.874+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-12T01:18:24.875+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data-pipeline-project/product_data_scraper.py']
[2024-12-12T01:18:24.878+0000] {subprocess.py:99} INFO - Output:
[2024-12-12T01:23:25.332+0000] {subprocess.py:106} INFO - 320번 데이터 수집 시작
[2024-12-12T01:23:25.334+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2024-12-12T01:23:25.334+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 92, in <module>
[2024-12-12T01:23:25.335+0000] {subprocess.py:106} INFO -     collect_all(320)
[2024-12-12T01:23:25.335+0000] {subprocess.py:106} INFO -   File "/opt/***/data-pipeline-project/product_data_scraper.py", line 58, in collect_all
[2024-12-12T01:23:25.336+0000] {subprocess.py:106} INFO -     drivers = [webdriver.Remote(
[2024-12-12T01:23:25.336+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^
[2024-12-12T01:23:25.336+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
[2024-12-12T01:23:25.337+0000] {subprocess.py:106} INFO -     self.start_session(capabilities)
[2024-12-12T01:23:25.337+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
[2024-12-12T01:23:25.337+0000] {subprocess.py:106} INFO -     response = self.execute(Command.NEW_SESSION, caps)["value"]
[2024-12-12T01:23:25.338+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-12T01:23:25.338+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
[2024-12-12T01:23:25.338+0000] {subprocess.py:106} INFO -     self.error_handler.check_response(response)
[2024-12-12T01:23:25.338+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
[2024-12-12T01:23:25.339+0000] {subprocess.py:106} INFO -     raise exception_class(message, screen, stacktrace)
[2024-12-12T01:23:25.339+0000] {subprocess.py:106} INFO - selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. New session request timed out
[2024-12-12T01:23:25.339+0000] {subprocess.py:106} INFO - Host info: host: 'de52ee8debf3', ip: '172.18.0.3'
[2024-12-12T01:23:25.339+0000] {subprocess.py:106} INFO - Build info: version: '4.20.0', revision: '866c76ca80'
[2024-12-12T01:23:25.339+0000] {subprocess.py:106} INFO - System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.14-linuxkit', java.version: '17.0.11'
[2024-12-12T01:23:25.340+0000] {subprocess.py:106} INFO - Driver info: driver.version: unknown
[2024-12-12T01:23:25.340+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-12T01:23:25.340+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:221)
[2024-12-12T01:23:25.340+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:68)
[2024-12-12T01:23:25.340+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
[2024-12-12T01:23:25.341+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.341+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-12T01:23:25.341+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.341+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:128)
[2024-12-12T01:23:25.341+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:87)
[2024-12-12T01:23:25.341+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-12T01:23:25.342+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-12T01:23:25.342+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.342+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.router.Router.execute (Router.java:87)
[2024-12-12T01:23:25.342+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
[2024-12-12T01:23:25.342+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-12T01:23:25.342+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-12T01:23:25.343+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.343+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:270)
[2024-12-12T01:23:25.343+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.343+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-12T01:23:25.343+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.343+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-12T01:23:25.344+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.344+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-12T01:23:25.344+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.344+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:346)
[2024-12-12T01:23:25.344+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Route.execute (Route.java:69)
[2024-12-12T01:23:25.345+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
[2024-12-12T01:23:25.345+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-12-12T01:23:25.345+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-12T01:23:25.345+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
[2024-12-12T01:23:25.345+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)
[2024-12-12T01:23:25.345+0000] {subprocess.py:106} INFO -     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
[2024-12-12T01:23:25.345+0000] {subprocess.py:106} INFO -     at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
[2024-12-12T01:23:25.346+0000] {subprocess.py:106} INFO -     at java.util.concurrent.FutureTask.run (None:-1)
[2024-12-12T01:23:25.346+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
[2024-12-12T01:23:25.346+0000] {subprocess.py:106} INFO -     at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
[2024-12-12T01:23:25.346+0000] {subprocess.py:106} INFO -     at java.lang.Thread.run (None:-1)
[2024-12-12T01:23:25.393+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2024-12-12T01:23:25.398+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-12T01:23:25.403+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_etl, task_id=collect_data, run_id=scheduled__2024-12-10T04:00:00+00:00, execution_date=20241210T040000, start_date=20241212T011824, end_date=20241212T012325
[2024-12-12T01:23:25.408+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T01:23:25.409+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task collect_data (Bash command failed. The command returned a non-zero exit code 1.; 262)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-12T01:23:25.428+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-12T01:23:25.435+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T01:23:25.435+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
