[2024-11-24T04:13:54.006+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T04:13:54.015+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T04:05:20.425926+00:00 [queued]>
[2024-11-24T04:13:54.020+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T04:05:20.425926+00:00 [queued]>
[2024-11-24T04:13:54.020+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-24T04:13:54.027+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_data> on 2024-11-24 04:05:20.425926+00:00
[2024-11-24T04:13:54.028+0000] {standard_task_runner.py:72} INFO - Started process 40 to run task
[2024-11-24T04:13:54.030+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_etl', 'collect_data', 'manual__2024-11-24T04:05:20.425926+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_auto.py', '--cfg-path', '/tmp/tmpvvmm03_1']
[2024-11-24T04:13:54.032+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask collect_data
[2024-11-24T04:13:54.058+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T04:05:20.425926+00:00 [running]> on host c6ae8df9a3c1
[2024-11-24T04:13:54.104+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_etl' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T04:05:20.425926+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-24T04:05:20.425926+00:00'
[2024-11-24T04:13:54.104+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T04:13:54.137+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-24T04:13:54.138+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data-pipeline-project/product_data_scraper.py']
[2024-11-24T04:13:54.141+0000] {subprocess.py:99} INFO - Output:
[2024-11-24T04:31:05.895+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-24T04:31:05.906+0000] {process_utils.py:132} INFO - Sending 15 to group 40. PIDs of all processes in the group: [42, 40]
[2024-11-24T04:31:05.911+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 40
[2024-11-24T04:31:05.916+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-24T04:31:05.926+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-11-24T04:31:05.972+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-24T04:31:05.984+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_pipeline_etl, task_id=collect_data, run_id=manual__2024-11-24T04:05:20.425926+00:00, execution_date=20241124T040520, start_date=20241124T041354, end_date=20241124T043105
[2024-11-24T04:31:06.010+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T04:31:06.058+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=42, status='terminated', started='04:13:53') (42) terminated with exit code None
[2024-11-24T04:31:06.059+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=40, status='terminated', exitcode=2, started='04:13:53') (40) terminated with exit code 2
[2024-11-24T04:31:06.060+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-11-24T04:31:06.088+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-24T04:31:09.666+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T04:31:09.678+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: data_pipeline_etl.collect_data manual__2024-11-24T04:05:20.425926+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-11-24T04:31:09.679+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
